# Generated by Django 4.2.2 on 2024-09-04 13:35

from django.db import migrations, models
import django.db.models.deletion

BRANDS = [
    {
        'name': 'Utility',
        'url': 'https://www.utilitytrailer.com/'
    },
    {
        'name': 'Great Dane',
        'url': 'https://greatdane.com/'
    },
    {
        'name': 'Transcraft',
        'url': 'https://www.startrailer.com/Manufacturers/Transcraft/'
    },
    {
        'name': 'Fontaine',
        'url': 'https://www.fontainetrailer.com/'
    },
    {
        'name': 'Reitnouer',
        'url': 'https://reitnouer-trailers.com/'
    },
    {
        'name': 'Wabash',
        'url': 'https://onewabash.com/'
    },
    {
        'name': 'Chaparral',
        'url': 'https://www.chaparralboats.com/'
    },
    {
        'name': 'Dorsey',
        'url': 'https://dorseytrailer.net/'
    },
    {
        'name': 'Vanguard',
        'url': 'https://www.vanguardtrailer.com/'
    },
    {
        'name': 'Ravens',
        'url': 'https://www.ravenssales.com/'
    },
    {
        'name': 'Wilson',
        'url': 'https://www.wilsontrailer.com/'
    },
    {
        'name': 'East',
        'url': 'https://www.intermountaintrailer.com/new-trailers/east-trailers/'
    }
]


def seed_new_manufacturers(apps, schema_editor):
    Manufacturer = apps.get_model('rent', 'Manufacturer')
    for brand in BRANDS:
        Manufacturer.objects.create(
            brand_name=brand['name'],
            url=brand['url'],
            type="semi")


def set_subtype_from_type(apps, schema_editor):
    Trailer = apps.get_model('rent', 'Trailer')
    for trailer in Trailer.objects.all():
        trailer.subtype = trailer.type
        trailer.type = "hotshot"
        trailer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_associated_phone_number_and_more'),
        ('rent', '0088_depositdiscount_saved_duration_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='insurance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='insuranced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.CharField(choices=[(
                'hotshot', 'hotshot'), ('semi', 'Semi')], default='hotshot', max_length=20),
        ),
        migrations.AddField(
            model_name='trailer',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trailer',
            name='initial_maintenance_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='trailer_owner', to='users.associated'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='ownership',
            field=models.CharField(
                choices=[('towit', 'TOWIT'), ('admin', 'ADMIN')], default='towit', max_length=20),
        ),
        migrations.AddField(
            model_name='trailer',
            name='size',
            field=models.CharField(blank=True, choices=[(
                '4896', '48-96'), ('48102', '48-102'), ('5396', '53-96'), ('53102', '53-102')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='subtype',
            field=models.CharField(choices=[('flatbed', 'Flatbed'), ('dryvan', 'Dry Van'), ('refrigerated', 'Refrigerated'), ('stepdeck', 'Step Deck'), ('lowboy', 'Lowboy'), ('dropdeck', 'Drop Deck'), ('enddump', 'End Dump'), (
                '6_car', '6-Car'), ('3_car_w', '3-Car Wedge'), ('3_car_l', '3-Car Low profile'), ('3_car_f', '3-Car Flatbed'), ('mini5', 'Mini-5'), ('ez4', 'EZ-4'), ('other', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(choices=[(
                'hotshot', 'hotshot'), ('semi', 'Semi')], default='hotshot', max_length=20),
        ),
        migrations.RunPython(set_subtype_from_type),
        migrations.RunPython(seed_new_manufacturers),
    ]
