# Generated by Django 4.2.2 on 2024-09-19 15:41

from django.db import migrations

def create_document_categories(apps, schema_editor):
    DocumentCategory = apps.get_model('inventory', 'DocumentCategory')
    DocumentCategory.objects.create(name='Registration', description='Category for registration documents.')
    DocumentCategory.objects.create(name='Inspection', description='Category for inspection documents.')
    DocumentCategory.objects.create(name='Others', description='Category for other documents.')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_documentcategory'),
    ]

    operations = [
        migrations.RunPython(create_document_categories),
    ]
